## Creating series

In [2]:
import pandas as pd

In [3]:
l = [1, 2, 3]
s1 = pd.Series(l)
print(s1)
print(type(s1))

0    1
1    2
2    3
dtype: int64
<class 'pandas.core.series.Series'>

In [4]:
l = (1, 2, 3)
s1 = pd.Series(l)
print(s1)
print(type(s1))

0    1
1    2
2    3
dtype: int64
<class 'pandas.core.series.Series'>

In [5]:
import numpy as np
arr = ([1, 2, 3])
s1 = pd.Series(arr)
print(s1)
print(type(s1))

0    1
1    2
2    3
dtype: int64
<class 'pandas.core.series.Series'>

In [6]:
l = [1, 2, 3]
s1 = pd.Series(l, name = "Demo")
print(s1)
print(type(s1))

0    1
1    2
2    3
Name: Demo, dtype: int64
<class 'pandas.core.series.Series'>

In [7]:
l = [1, 2, 3]
labels = ['first', 'second', 'third']
s1 = pd.Series(l, name = "Demo", index = labels)
print(s1)
print(type(s1))

first     1
second    2
third     3
Name: Demo, dtype: int64
<class 'pandas.core.series.Series'>

# Dataframe

In [8]:
# create dataframe from dictionary
marks = {
    'math': [10, 20, 30, 40, 50, 60, 70],
    'science': [55, 51, None, 87, 98, 88, 46],
    'computer': [11, 12, 33, 44, 55, 66, 77],
    'remarks': list("abbcaca")
}

df = pd.DataFrame(marks)
df

   math  science  computer remarks
0    10     55.0        11       a
1    20     51.0        12       b
2    30      NaN        33       b
3    40     87.0        44       c
4    50     98.0        55       a
5    60     88.0        66       c
6    70     46.0        77       a

In [9]:
marks_l = [
    [10, 55, 11],
    [20, 51, 22],
    [30, None, 33],
    [40, 87, 44],
    [50, 98, 55],
    [60, 88, 66],
    [70, 46, 77]
]
df2 = pd.DataFrame(marks_l, columns =[ "math", "science", "computer"])
df2

   math  science  computer
0    10     55.0        11
1    20     51.0        22
2    30      NaN        33
3    40     87.0        44
4    50     98.0        55
5    60     88.0        66
6    70     46.0        77

In [10]:
df['math']

0    10
1    20
2    30
3    40
4    50
5    60
6    70
Name: math, dtype: int64

In [11]:
df.math

0    10
1    20
2    30
3    40
4    50
5    60
6    70
Name: math, dtype: int64

In [12]:
# accessing multiple column
df[["math", "science"]]

   math  science
0    10     55.0
1    20     51.0
2    30      NaN
3    40     87.0
4    50     98.0
5    60     88.0
6    70     46.0

In [13]:
df[['computer']]

   computer
0        11
1        12
2        33
3        44
4        55
5        66
6        77

In [14]:
# top n and bottom n
df.head(n = 3)

   math  science  computer remarks
0    10     55.0        11       a
1    20     51.0        12       b
2    30      NaN        33       b

In [15]:
df.tail(n = 2)

   math  science  computer remarks
5    60     88.0        66       c
6    70     46.0        77       a

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   math      7 non-null      int64
 1   science   6 non-null      float64
 2   computer  7 non-null      int64
 3   remarks   7 non-null      object
dtypes: float64(1), int64(2), object(1)
memory usage: 356.0+ bytes

In [17]:
new_reord = [[50, 39.0, 88, 'c']]
new_record_df = pd.DataFrame(new_reord, columns =[ "math", "science", "computer", "remarks"])
new_record_df

   math  science  computer remarks
0    50     39.0        88       c

In [18]:
pd.concat([df, new_record_df])

   math  science  computer remarks
0    10     55.0        11       a
1    20     51.0        12       b
2    30      NaN        33       b
3    40     87.0        44       c
4    50     98.0        55       a
5    60     88.0        66       c
6    70     46.0        77       a
0    50     39.0        88       c

In [19]:
df3 = pd.concat([new_record_df, df], ignore_index= True)
df3

   math  science  computer remarks
0    50     39.0        88       c
1    10     55.0        11       a
2    20     51.0        12       b
3    30      NaN        33       b
4    40     87.0        44       c
5    50     98.0        55       a
6    60     88.0        66       c
7    70     46.0        77       a

In [20]:
df3.describe()

            math    science   computer
count   8.000000   7.000000   8.000000
mean   41.250000  66.285714  48.250000
std    20.310096  23.886637  28.584461
min    10.000000  39.000000  11.000000
25%    27.500000  48.500000  27.750000
50%    45.000000  55.000000  49.500000
75%    52.500000  87.500000  68.750000
max    70.000000  98.000000  88.000000

In [21]:
df3['computer'].min()

np.int64(11)

In [22]:
df3['computer'].max()

np.int64(88)

In [23]:
df3['computer'].argmin()

np.int64(1)

In [24]:
df3['computer'].argmax()

np.int64(0)

In [25]:
df3['computer'].to_list()

[88, 11, 12, 33, 44, 55, 66, 77]

In [26]:
df3['computer'].to_numpy()

array([88, 11, 12, 33, 44, 55, 66, 77])

In [27]:
df3['computer'].to_csv("./files/temp_data.csv")

In [28]:
df3[['science', 'computer']].to_csv("./files/temp_data.csv", index = False)

In [29]:
df['math'] - 1

0     9
1    19
2    29
3    39
4    49
5    59
6    69
Name: math, dtype: int64

In [30]:
df3['math'] = df3['math'] - 1
df3['math']

0    49
1     9
2    19
3    29
4    39
5    49
6    59
7    69
Name: math, dtype: int64

In [31]:
df3['math']

0    49
1     9
2    19
3    29
4    39
5    49
6    59
7    69
Name: math, dtype: int64

In [32]:
df3

   math  science  computer remarks
0    49     39.0        88       c
1     9     55.0        11       a
2    19     51.0        12       b
3    29      NaN        33       b
4    39     87.0        44       c
5    49     98.0        55       a
6    59     88.0        66       c
7    69     46.0        77       a

In [33]:
df3['computer'] + df3['math'] + df3['science']

0    176.0
1     75.0
2     82.0
3      NaN
4    170.0
5    202.0
6    213.0
7    192.0
dtype: float64

In [34]:
df3['total'] = df3['computer'] + df3['math'] + df3['science']
df3

   math  science  computer remarks  total
0    49     39.0        88       c  176.0
1     9     55.0        11       a   75.0
2    19     51.0        12       b   82.0
3    29      NaN        33       b    NaN
4    39     87.0        44       c  170.0
5    49     98.0        55       a  202.0
6    59     88.0        66       c  213.0
7    69     46.0        77       a  192.0

In [35]:
# check NAN
df3.isna()

    math  science  computer  remarks  total
0  False    False     False    False  False
1  False    False     False    False  False
2  False    False     False    False  False
3  False     True     False    False   True
4  False    False     False    False  False
5  False    False     False    False  False
6  False    False     False    False  False
7  False    False     False    False  False

In [36]:
df3.isna().sum()

math        0
science     1
computer    0
remarks     0
total       1
dtype: int64

In [37]:
new_record = [[69, 46.0, 77, 'a', 192.0]]
new_record_df = pd.DataFrame(new_record, columns = ["math" , "science", "computer", "remarks", "total"])
new_record_df

   math  science  computer remarks  total
0    69     46.0        77       a  192.0

In [38]:
df3 = pd.concat([new_record_df , df3], ignore_index = True)
df3

   math  science  computer remarks  total
0    69     46.0        77       a  192.0
1    49     39.0        88       c  176.0
2     9     55.0        11       a   75.0
3    19     51.0        12       b   82.0
4    29      NaN        33       b    NaN
5    39     87.0        44       c  170.0
6    49     98.0        55       a  202.0
7    59     88.0        66       c  213.0
8    69     46.0        77       a  192.0

In [39]:
df3.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8     True
dtype: bool

In [40]:
df3 = df3.drop_duplicates()
df3

   math  science  computer remarks  total
0    69     46.0        77       a  192.0
1    49     39.0        88       c  176.0
2     9     55.0        11       a   75.0
3    19     51.0        12       b   82.0
4    29      NaN        33       b    NaN
5    39     87.0        44       c  170.0
6    49     98.0        55       a  202.0
7    59     88.0        66       c  213.0

In [41]:
df3.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

In [42]:
df3['science'].fillna(0)
# df3['science'] = df3['science'].fillna(0)

0    46.0
1    39.0
2    55.0
3    51.0
4     0.0
5    87.0
6    98.0
7    88.0
Name: science, dtype: float64

In [43]:
science_median = df3['science'].median()
science_median

np.float64(55.0)

In [44]:
df3['science'] = df3['science'].fillna(science_median)

C:\Users\User\AppData\Local\Temp\ipykernel_26220\3581608768.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['science'] = df3['science'].fillna(science_median)

In [45]:
df3

   math  science  computer remarks  total
0    69     46.0        77       a  192.0
1    49     39.0        88       c  176.0
2     9     55.0        11       a   75.0
3    19     51.0        12       b   82.0
4    29     55.0        33       b    NaN
5    39     87.0        44       c  170.0
6    49     98.0        55       a  202.0
7    59     88.0        66       c  213.0

In [46]:
df3['remarks'].unique()

array(['a', 'c', 'b'], dtype=object)

In [47]:
df3['math'].unique()

array([69, 49,  9, 19, 29, 39, 59])

In [48]:
df3['remarks'].nunique()

3

In [49]:
df3

   math  science  computer remarks  total
0    69     46.0        77       a  192.0
1    49     39.0        88       c  176.0
2     9     55.0        11       a   75.0
3    19     51.0        12       b   82.0
4    29     55.0        33       b    NaN
5    39     87.0        44       c  170.0
6    49     98.0        55       a  202.0
7    59     88.0        66       c  213.0

In [50]:
df3.drop(labels= ["total"], axis= 1, inplace= True) # if row wise axis = 0, if column wise axis = 1

C:\Users\User\AppData\Local\Temp\ipykernel_26220\3323666705.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3.drop(labels= ["total"], axis= 1, inplace= True) # if row wise axis = 0, if column wise axis = 1

In [51]:
df3

   math  science  computer remarks
0    69     46.0        77       a
1    49     39.0        88       c
2     9     55.0        11       a
3    19     51.0        12       b
4    29     55.0        33       b
5    39     87.0        44       c
6    49     98.0        55       a
7    59     88.0        66       c

In [52]:
df3.rename(
    columns = {
        'math':'mathematics',
        'computer': "comp"
    },
    inplace = True
)
df3

C:\Users\User\AppData\Local\Temp\ipykernel_26220\4179631645.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3.rename(

   mathematics  science  comp remarks
0           69     46.0    77       a
1           49     39.0    88       c
2            9     55.0    11       a
3           19     51.0    12       b
4           29     55.0    33       b
5           39     87.0    44       c
6           49     98.0    55       a
7           59     88.0    66       c

In [53]:
df3['grade'] = df3['remarks']
df3

C:\Users\User\AppData\Local\Temp\ipykernel_26220\2590514196.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['grade'] = df3['remarks']

   mathematics  science  comp remarks grade
0           69     46.0    77       a     a
1           49     39.0    88       c     c
2            9     55.0    11       a     a
3           19     51.0    12       b     b
4           29     55.0    33       b     b
5           39     87.0    44       c     c
6           49     98.0    55       a     a
7           59     88.0    66       c     c

In [56]:
grade_mapper = {'a': 0, 'b':1, 'c':2}
df3['grade'] = df3['grade'].map(grade_mapper)
df3

C:\Users\User\AppData\Local\Temp\ipykernel_26220\796432195.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['grade'] = df3['grade'].map(grade_mapper)

   mathematics  science  comp remarks  grade
0           69     46.0    77       a    NaN
1           49     39.0    88       c    NaN
2            9     55.0    11       a    NaN
3           19     51.0    12       b    NaN
4           29     55.0    33       b    NaN
5           39     87.0    44       c    NaN
6           49     98.0    55       a    NaN
7           59     88.0    66       c    NaN